name: musify
description: Music Streaming app made in Flutter!
homepage: https://github.com/gokadzev/Musify
repository: https://github.com/gokadzev/Musify
issue_tracker: https://github.com/gokadzev/Musify/issues

publish_to: 'none'
version: 7.2.0+77 # run update.sh after changing the version

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ^3.16.7

dependencies:
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  background_downloader: ^8.0.5
  cached_network_image: ^3.3.1
  dynamic_color: ^1.6.9
  file_picker: ^6.1.1
  fluentui_system_icons: ^1.1.223
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.1.2
  intl: ^0.18.0
  just_audio: ^0.9.36
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  rxdart: ^0.27.7
  url_launcher: ^6.2.3
  youtube_explode_dart: ^2.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/roboto/
    - assets/fonts/paytone/

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash.png
  color_dark: '#151515'
  image_dark: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/splash.png
    icon_background_color_dark: '#151515'

flutter_launcher_icons:
  android: 'launcher_icon'
  adaptive_icon_background: '#191919'
  adaptive_icon_foreground: 'assets/images/ic_launcher_foreground.png'
  adaptive_icon_round: 'assets/images/ic_launcher_round.png'
  image_path: 'assets/images/ic_launcher.png'
